/*
MongoDB seed data for StreetFoodNarratorDB
Run with:
  mongosh < d:/project/street_food/Database/SeedData.mongodb.js
*/

db = db.getSiblingDB('StreetFoodNarratorDB');

// Clear existing data
['pois','audio_contents','tours','poi_tours','counters'].forEach((name) => db[name].deleteMany({}));

// POIs
const now = new Date();

db.pois.insertMany([
  {
    POI_ID: 1,
    Latitude: 10.761905898335831,
    Longitude: 106.70222716527056,
    TriggerRadius: 80,
    Priority: 10,
    Name_Vi: 'Cổng vào Phố Ẩm thực Vĩnh Khánh',
    Name_En: 'Vinh Khanh Food Street Entrance',
    Description_Vi: 'Biển chào "Phố Ẩm thực Vĩnh Khánh" – nơi bắt đầu hành trình khám phá thiên đường hải sản sầm uất nhất Quận 4. Được Time Out bình chọn là một trong 10 đường phố thú vị nhất thế giới năm 2025.',
    Description_En: 'The welcoming gate of "Vinh Khanh Food Street" - the start of your journey to explore District 4\'s busiest seafood paradise. Ranked as one of the 10 coolest streets in the world for 2025 by Time Out.',
    SignatureDish: 'Hải sản tươi sống (Seafood)',
    FunFact: 'Đây là điểm quét QR code để bắt đầu tour thuyết minh tự động.',
    EstimatedHoursText: '17:00-23:00',
    Type: 'LandMark',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    POI_ID: 2,
    Latitude: 10.761518431027818,
    Longitude: 106.70271542519974,
    TriggerRadius: 50,
    Priority: 7,
    Name_Vi: 'Ốc Vũ',
    Name_En: 'Vu Snails',
    Description_Vi: 'Nằm tại 37 Vĩnh Khánh, quán thu hút đông đảo giới trẻ bởi thực đơn đa dạng và giá cả cực kỳ bình dân. Các món nướng tại đây luôn nóng hổi và đậm đà.',
    Description_En: 'Located at 37 Vinh Khanh, this spot attracts many youngsters with its diverse menu and very affordable prices. The grilled dishes here are always hot and flavorful.',
    SignatureDish: 'Ốc xào bơ tỏi, Hải sản nướng',
    FunFact: 'Giá cực mềm, phù hợp cho học sinh sinh viên.',
    EstimatedHoursText: '15:00-00:00',
    Type: 'Restaurant',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    POI_ID: 3,
    Latitude: 10.761795162597451,
    Longitude: 106.70239298897182,
    TriggerRadius: 50,
    Priority: 7,
    Name_Vi: 'Ốc Thảo',
    Name_En: 'Thao Snails',
    Description_Vi: 'Địa chỉ 383 Vĩnh Khánh. Quán nổi tiếng với không gian rộng rãi, sạch sẽ và cách chế biến món ăn cầu kỳ, giữ được độ ngọt tự nhiên của hải sản.',
    Description_En: 'Located at 383 Vinh Khanh. Famous for its spacious and clean area. The cooking techniques are meticulous, preserving the natural sweetness of the seafood.',
    SignatureDish: 'Ốc len xào dừa, Sò điệp nướng mỡ hành',
    FunFact: 'Thực đơn phong phú với hơn 30 loại ốc khác nhau.',
    EstimatedHoursText: '14:00-23:00',
    Type: 'Restaurant',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    POI_ID: 4,
    Latitude: 10.761038078500885,
    Longitude: 106.70290444809687,
    TriggerRadius: 50,
    Priority: 8,
    Name_Vi: 'Ốc Sáu Nở',
    Name_En: 'Sau No Snails',
    Description_Vi: 'Tọa lạc tại khu vực 121-128 Vĩnh Khánh, đây là một trong những quán ốc vỉa hè đời đầu với không gian sôi động, đậm chất đường phố Sài Gòn.',
    Description_En: 'Situated at 121-128 Vinh Khanh, this is one of the original sidewalk snail stalls with a vibrant atmosphere, quintessential of Saigon street style.',
    SignatureDish: 'Nghêu hấp sả, Ốc hương rang muối',
    FunFact: 'Tươi ngon và náo nhiệt là những từ khóa khi nhắc đến Sáu Nở.',
    EstimatedHoursText: '16:00-23:30',
    Type: 'Stall',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    POI_ID: 5,
    Latitude: 10.760848629826567,
    Longitude: 106.7032957744219,
    TriggerRadius: 60,
    Priority: 9,
    Name_Vi: 'Ốc Oanh',
    Name_En: 'Oanh Snails',
    Description_Vi: 'Quán lão làng với tuổi đời hơn 20 năm tại 534 Vĩnh Khánh. Nổi tiếng nhất với các món ốc sốt bơ tỏi và đặc biệt được vinh danh trong danh mục Bib Gourmand của Michelin.',
    Description_En: 'A legendary spot with over 20 years of history at 534 Vinh Khanh. Most famous for its butter garlic sauce and specially honored in the Michelin Bib Gourmand list.',
    SignatureDish: 'Ốc hương xào bơ tỏi, Ốc bươu nướng phô mai',
    FunFact: 'Đứng đầu danh sách những quán phải thử khi đến Vĩnh Khánh.',
    EstimatedHoursText: '15:00-23:00',
    Type: 'Restaurant',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    POI_ID: 6,
    Latitude: 10.760806933075282,
    Longitude: 106.70347875218654,
    TriggerRadius: 50,
    Priority: 6,
    Name_Vi: 'A Fat Hot Pot',
    Name_En: 'A Fat Hot Pot',
    Description_Vi: 'Nằm tại 668 Vĩnh Khánh, quán chuyên về lẩu và nướng tự chọn. Không gian rộng thoáng, rất phù hợp cho những buổi tụ tập nhóm đông người.',
    Description_En: 'Located at 668 Vinh Khanh, specialized in self-selected hot pot and BBQ. The spacious and airy environment makes it ideal for large group gatherings.',
    SignatureDish: 'Lẩu hải sản, Hàu sữa nướng',
    FunFact: 'Phong cách buffet tại bàn rất được ưa chuộng.',
    EstimatedHoursText: '16:00-23:00',
    Type: 'Restaurant',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    POI_ID: 7,
    Latitude: 10.760794431975599,
    Longitude: 106.7036590681073,
    TriggerRadius: 50,
    Priority: 6,
    Name_Vi: 'Chilli Lẩu Nướng Tự Chọn',
    Name_En: 'Chilli BBQ & Hot Pot',
    Description_Vi: 'Địa chỉ 232 Vĩnh Khánh. Đây là điểm đến quen thuộc của giới trẻ với các món lẩu nướng đa dạng, từ hải sản đến thịt bò Mỹ cao cấp.',
    Description_En: 'Address: 232 Vinh Khanh. A popular destination for youngsters, offering a variety of BBQ and hot pot dishes from seafood to premium US beef.',
    SignatureDish: 'Lẩu nướng hải sản, Bò Mỹ nướng',
    FunFact: 'Gia vị ướp đậm đà là đặc trưng riêng của Chilli.',
    EstimatedHoursText: '16:00-00:00',
    Type: 'Restaurant',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    POI_ID: 8,
    Latitude: 10.761127163188009,
    Longitude: 106.70475425408135,
    TriggerRadius: 50,
    Priority: 7,
    Name_Vi: 'Alo Quán – Seafood & Beer',
    Name_En: 'Alo Quan - Seafood & Beer',
    Description_Vi: 'Tọa lạc tại 333 Vĩnh Khánh, Alo Quán mang phong cách hiện đại, chill, phù hợp cho những buổi nhậu đêm thoải mái bên gia đình và bạn bè.',
    Description_En: 'Located at 333 Vinh Khanh, Alo Quan offers a modern, chill style, perfect for late-night drinking and relaxing with family and friends.',
    SignatureDish: 'Tôm sốt Thái, Nghêu hấp sả',
    FunFact: 'Không gian mở rất thoáng và view ngắm phố cực đẹp.',
    EstimatedHoursText: '15:00-01:00',
    Type: 'Restaurant',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    POI_ID: 9,
    Latitude: 10.761347965170131,
    Longitude: 106.70496784739889,
    TriggerRadius: 50,
    Priority: 8,
    Name_Vi: 'Ốc Đào 2',
    Name_En: 'Dao Snails 2',
    Description_Vi: 'Chi nhánh nổi tiếng tại 232/123 Vĩnh Khánh. Ốc Đào nổi danh nhờ nước chấm đặc trưng và thực đơn phong phú với hơn 30 cách chế biến khác nhau.',
    Description_En: 'A famous branch at 232/123 Vinh Khanh. Dao Snails is renowned for its signature dipping sauce and a rich menu with over 30 different cooking styles.',
    SignatureDish: 'Ốc sốt trứng muối, Ốc me',
    FunFact: 'Thương hiệu ốc top đầu Sài Gòn nay đã có mặt tại Vĩnh Khánh.',
    EstimatedHoursText: '12:00-22:00',
    Type: 'Restaurant',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    POI_ID: 10,
    Latitude: 10.761149988188182,
    Longitude: 106.70538401196282,
    TriggerRadius: 50,
    Priority: 6,
    Name_Vi: 'Làng Quán',
    Name_En: 'Lang Quan',
    Description_Vi: 'Nằm ở đoạn giữa phố (khu vực 500-600), Làng Quán là lựa chọn tuyệt vời cho các nhóm nhậu với menu lẩu nướng và hải sản vô cùng đa dạng.',
    Description_En: 'Located in the middle of the street (area 500-600), Lang Quan is a great choice for drinking groups with an extremely diverse BBQ and seafood menu.',
    SignatureDish: 'Lẩu hải sản nướng, Bạch tuộc nướng',
    FunFact: 'Giá cả ổn định và phục vụ nhanh nhẹn.',
    EstimatedHoursText: '16:00-00:00',
    Type: 'Restaurant',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    POI_ID: 11,
    Latitude: 10.761185236052697,
    Longitude: 106.70570361039157,
    TriggerRadius: 50,
    Priority: 7,
    Name_Vi: 'Ớt Xiêm Quán',
    Name_En: 'Ot Xiem Quan',
    Description_Vi: 'Nằm tại 568 Vĩnh Khánh, quán nổi bật với các món hải sản được chế biến cầu kỳ theo phong cách riêng, không chỉ giới hạn ở các món ốc.',
    Description_En: 'Located at 568 Vinh Khanh, this place stands out with elaborately prepared seafood dishes in its own style, not just limited to snail dishes.',
    SignatureDish: 'Cá điêu hồng rang muối Hồng Kông, Tôm sú mù tạt',
    FunFact: 'Điểm đến cho những ai thích khám phá hương vị hải sản mới lạ.',
    EstimatedHoursText: '16:00-23:00',
    Type: 'Restaurant',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    POI_ID: 12,
    Latitude: 10.761123552506971,
    Longitude: 106.70660690985743,
    TriggerRadius: 40,
    Priority: 7,
    Name_Vi: 'Bún Cá Châu Đốc Dì Tư',
    Name_En: 'Di Tu Chau Doc Fish Noodles',
    Description_Vi: 'Địa chỉ 320/79 Vĩnh Khánh. Quán mang hương vị bún cá miền Tây đặc trưng với nước dùng thanh ngọt từ cá và nghệ. Một sự thay đổi khẩu vị tuyệt vời sau các món nướng.',
    Description_En: 'Address: 320/79 Vinh Khanh. The stall brings the typical Western fish noodle flavor with a clear, sweet broth made from fish and turmeric. A great change of pace after grilled dishes.',
    SignatureDish: 'Bún cá đặc biệt, Bún mực',
    FunFact: 'Có phục vụ cả buổi sáng sớm cho khách ghé phố.',
    EstimatedHoursText: '06:00-21:00',
    Type: 'Restaurant',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  }
]);

// Audio contents

db.audio_contents.insertMany([
  {
    AudioContent_ID: 1,
    POI_ID: 1,
    Title: 'TTS',
    Description: '',
    Language: 'vi-VN',
    AudioUrl: '',
    Duration: 20,
    FileSize: null,
    TTSText: 'Chào mừng bạn đến với Phố Ẩm thực Vĩnh Khánh! Đây là thiên đường hải sản sầm uất nhất Quận 4, được Time Out bình chọn là một trong 10 đường phố thú vị nhất thế giới. Hãy chuẩn bị khám phá hành trình ẩm thực đặc sắc với chúng tôi!',

    Format: 'mp3',
    Bitrate: 128,
    TTSVoice: '',
    TTSProvider: 'edge-tts',
    TTSSpeed: 1.0,
    TTSPitch: 0,
    TTSConfig: { voice: '', speed: 1.0, pitch: 0, volume: 1.0, provider: 'edge-tts' },
    TemplateId: 'template_001',
    TemplateName: 'Giới thiệu món ăn (Chuẩn)',
    TemplateVariables: {},
    PlayCount: 0,
    DownloadCount: 0,
    CompletionRate: null,
    AverageListenTime: null,
    SkipRate: null,
    Version: 1,
    PreviousVersionId: null,
    PublishedAt: now,
    Status: 'published',
    CreatedByRole: 'Admin',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    AudioContent_ID: 2,
    POI_ID: 1,
    Title: 'TTS',
    Description: '',
    Language: 'en-US',
    AudioUrl: '',
    Duration: 18,
    FileSize: null,
    TTSText: 'Welcome to Vinh Khanh Food Street! This is District 4\'s busiest seafood paradise, ranked as one of the 10 coolest streets in the world by Time Out. Get ready to explore an amazing culinary journey with us!',

    Format: 'mp3',
    Bitrate: 128,
    TTSVoice: '',
    TTSProvider: 'edge-tts',
    TTSSpeed: 1.0,
    TTSPitch: 0,
    TTSConfig: { voice: '', speed: 1.0, pitch: 0, volume: 1.0, provider: 'edge-tts' },
    TemplateId: 'template_001',
    TemplateName: 'Giới thiệu món ăn (Chuẩn)',
    TemplateVariables: {},
    PlayCount: 0,
    DownloadCount: 0,
    CompletionRate: null,
    AverageListenTime: null,
    SkipRate: null,
    Version: 1,
    PreviousVersionId: null,
    PublishedAt: now,
    Status: 'published',
    CreatedByRole: 'Admin',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    AudioContent_ID: 3,
    POI_ID: 2,
    Title: 'TTS',
    Description: '',
    Language: 'vi-VN',
    AudioUrl: '',
    Duration: 15,
    FileSize: null,
    TTSText: 'Bạn đang đến gần Ốc Vũ, quán ốc bình dân được giới trẻ yêu thích. Với thực đơn đa dạng và giá cả phải chăng, đây là điểm dừng chân lý tưởng cho học sinh sinh viên. Các món nướng ở đây luôn nóng hổi và đậm đà.',

    Format: 'mp3',
    Bitrate: 128,
    TTSVoice: '',
    TTSProvider: 'edge-tts',
    TTSSpeed: 1.0,
    TTSPitch: 0,
    TTSConfig: { voice: '', speed: 1.0, pitch: 0, volume: 1.0, provider: 'edge-tts' },
    TemplateId: 'template_001',
    TemplateName: 'Giới thiệu món ăn (Chuẩn)',
    TemplateVariables: {},
    PlayCount: 0,
    DownloadCount: 0,
    CompletionRate: null,
    AverageListenTime: null,
    SkipRate: null,
    Version: 1,
    PreviousVersionId: null,
    PublishedAt: now,
    Status: 'published',
    CreatedByRole: 'Admin',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    AudioContent_ID: 4,
    POI_ID: 5,
    Title: 'TTS',
    Description: '',
    Language: 'vi-VN',
    AudioUrl: '',
    Duration: 22,
    FileSize: null,
    TTSText: 'Chào mừng bạn đến với Ốc Oanh - quán ốc huyền thoại với hơn 20 năm tuổi đời! Quán được vinh danh trong danh mục Bib Gourmand của Michelin. Món ốc hương xào bơ tỏi và ốc bươu nướng phô mai là đặc sản không thể bỏ qua.',

    Format: 'mp3',
    Bitrate: 128,
    TTSVoice: '',
    TTSProvider: 'edge-tts',
    TTSSpeed: 1.0,
    TTSPitch: 0,
    TTSConfig: { voice: '', speed: 1.0, pitch: 0, volume: 1.0, provider: 'edge-tts' },
    TemplateId: 'template_001',
    TemplateName: 'Giới thiệu món ăn (Chuẩn)',
    TemplateVariables: {},
    PlayCount: 0,
    DownloadCount: 0,
    CompletionRate: null,
    AverageListenTime: null,
    SkipRate: null,
    Version: 1,
    PreviousVersionId: null,
    PublishedAt: now,
    Status: 'published',
    CreatedByRole: 'Admin',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    AudioContent_ID: 5,
    POI_ID: 5,
    Title: 'TTS',
    Description: '',
    Language: 'en-US',
    AudioUrl: '',
    Duration: 20,
    FileSize: null,
    TTSText: 'Welcome to Oanh Snails - a legendary restaurant with over 20 years of history! Honored in the Michelin Bib Gourmand list. The butter garlic snails and grilled cheese escargot are must-try specialties.',

    Format: 'mp3',
    Bitrate: 128,
    TTSVoice: '',
    TTSProvider: 'edge-tts',
    TTSSpeed: 1.0,
    TTSPitch: 0,
    TTSConfig: { voice: '', speed: 1.0, pitch: 0, volume: 1.0, provider: 'edge-tts' },
    TemplateId: 'template_001',
    TemplateName: 'Giới thiệu món ăn (Chuẩn)',
    TemplateVariables: {},
    PlayCount: 0,
    DownloadCount: 0,
    CompletionRate: null,
    AverageListenTime: null,
    SkipRate: null,
    Version: 1,
    PreviousVersionId: null,
    PublishedAt: now,
    Status: 'published',
    CreatedByRole: 'Admin',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    AudioContent_ID: 6,
    POI_ID: 9,
    Title: 'TTS',
    Description: '',
    Language: 'vi-VN',
    AudioUrl: '',
    Duration: 15,
    FileSize: null,
    TTSText: 'Bạn đang đến gần Ốc Đào 2. Quán nổi tiếng với nước chấm đặc trưng và hơn 30 cách chế biến ốc khác nhau. Món ốc sốt trứng muối và ốc me là những món đặc sản phải thử!',

    Format: 'mp3',
    Bitrate: 128,
    TTSVoice: '',
    TTSProvider: 'edge-tts',
    TTSSpeed: 1.0,
    TTSPitch: 0,
    TTSConfig: { voice: '', speed: 1.0, pitch: 0, volume: 1.0, provider: 'edge-tts' },
    TemplateId: 'template_001',
    TemplateName: 'Giới thiệu món ăn (Chuẩn)',
    TemplateVariables: {},
    PlayCount: 0,
    DownloadCount: 0,
    CompletionRate: null,
    AverageListenTime: null,
    SkipRate: null,
    Version: 1,
    PreviousVersionId: null,
    PublishedAt: now,
    Status: 'published',
    CreatedByRole: 'Admin',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    AudioContent_ID: 7,
    POI_ID: 12,
    Title: 'TTS',
    Description: '',
    Language: 'vi-VN',
    AudioUrl: '',
    Duration: 14,
    FileSize: null,
    TTSText: 'Đây là Bún Cá Châu Đốc Dì Tư, mang hương vị miền Tây đích thực với nước dùng thanh ngọt từ cá và nghệ. Một sự thay đổi khẩu vị tuyệt vời sau những món hải sản nướng!',

    Format: 'mp3',
    Bitrate: 128,
    TTSVoice: '',
    TTSProvider: 'edge-tts',
    TTSSpeed: 1.0,
    TTSPitch: 0,
    TTSConfig: { voice: '', speed: 1.0, pitch: 0, volume: 1.0, provider: 'edge-tts' },
    TemplateId: 'template_001',
    TemplateName: 'Giới thiệu món ăn (Chuẩn)',
    TemplateVariables: {},
    PlayCount: 0,
    DownloadCount: 0,
    CompletionRate: null,
    AverageListenTime: null,
    SkipRate: null,
    Version: 1,
    PreviousVersionId: null,
    PublishedAt: now,
    Status: 'published',
    CreatedByRole: 'Admin',
    IsActive: true,
    CreatedAt: now,
    UpdatedAt: now
  }
]);

// Tour

db.tours.insertOne({
  Tour_ID: 1,
  TourName: 'Tour Ẩm Thực Vỉa Hè Sài Gòn',
  Description: 'Khám phá các món ăn vỉa hè đặc trưng của Sài Gòn tại khu vực Vĩnh Khánh',
  EstimatedDurationMinutes: 60,
  IsActive: true,
  CreatedAt: now,
  UpdatedAt: now
});

// Link POIs to Tour

db.poi_tours.insertMany([
  { POI_ID: 1, Tour_ID: 1, OrderIndex: 1 },
  { POI_ID: 2, Tour_ID: 1, OrderIndex: 2 },
  { POI_ID: 3, Tour_ID: 1, OrderIndex: 3 },
  { POI_ID: 4, Tour_ID: 1, OrderIndex: 4 }
]);

// Vendors

db.vendor_profiles.insertMany([
  {
    VendorId: 1,
    UserId: 'vendor_1',
    ContactName: 'Nguyễn Văn A',
    ContactEmail: 'nguyenvana@gmail.com',
    ContactPhone: '0901234567',
    BusinessName: 'Ẩm Thực A',
    BusinessDescription: 'Hải sản tươi sống Vĩnh Khánh.',
    Address: '37 Vĩnh Khánh, Q4, TP.HCM',
    IsVerified: true,
    VerificationStatus: 'approved',
    Rating: 4.8,
    ViewCount: 1200,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    VendorId: 2,
    UserId: 'vendor_2',
    ContactName: 'Trần Thị B',
    ContactEmail: 'tranthib@gmail.com',
    ContactPhone: '0902345678',
    BusinessName: 'Quán Ốc B',
    BusinessDescription: 'Quán ốc bình dân, giá mềm.',
    Address: '383 Vĩnh Khánh, Q4, TP.HCM',
    IsVerified: false,
    VerificationStatus: 'pending',
    Rating: null,
    ViewCount: 0,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    VendorId: 3,
    UserId: 'vendor_3',
    ContactName: 'Lê Văn C',
    ContactEmail: 'levanc@gmail.com',
    ContactPhone: '0903456789',
    BusinessName: 'Làng Quán',
    BusinessDescription: 'Quán nhậu vỉa hè, không gian thoáng.',
    Address: '500-600 Vĩnh Khánh, Q4, TP.HCM',
    IsVerified: true,
    VerificationStatus: 'approved',
    Rating: 4.5,
    ViewCount: 890,
    CreatedAt: now,
    UpdatedAt: now
  },
  {
    VendorId: 4,
    UserId: 'vendor_4',
    ContactName: 'Phạm Thị D',
    ContactEmail: 'phamthid@gmail.com',
    ContactPhone: '0904567890',
    BusinessName: 'Quán D',
    BusinessDescription: 'Vendor chưa được duyệt.',
    Address: '568 Vĩnh Khánh, Q4, TP.HCM',
    IsVerified: false,
    VerificationStatus: 'rejected',
    Rating: null,
    ViewCount: 0,
    CreatedAt: now,
    UpdatedAt: now
  }
]);

// Link POIs to Vendors

db.pois.updateMany({ POI_ID: { $in: [1, 2, 3, 4] } }, { $set: { VendorId: 1 } });
db.pois.updateMany({ POI_ID: { $in: [5, 6, 7, 8] } }, { $set: { VendorId: 2 } });
db.pois.updateMany({ POI_ID: { $in: [9, 10, 11, 12] } }, { $set: { VendorId: 3 } });

// Seed counters for sequential IDs

db.counters.insertMany([
  { _id: 'poi_id', Value: 12 },
  { _id: 'audio_content_id', Value: 7 },
  { _id: 'tour_id', Value: 1 },
  { _id: 'vendor_id', Value: 4 }
]);
