use('streetfood_narrator_db');

db.pois.deleteMany({});

db.counters.updateOne(
  { _id: 'poi_id' },
  { $set: { Value: 0 } },
  { upsert: true }
);


const pois = [

  {
    POI_ID: 1,
    Name_Vi: 'Cổng chào Phố Ẩm thực Vĩnh Khánh',
    Name_En: 'Vinh Khanh Food Street Entrance',
    Name_Zh: '永庆美食街入口',
    Description_Vi: 'Chào mừng bạn đến với Phố Ẩm thực Vĩnh Khánh – "thiên đường không ngủ" của Quận 4. Ngay khi bước qua cổng chào này, bạn sẽ cảm nhận được nhịp sống hối hả, rực rỡ và đầy mê hoặc của Sài Gòn về đêm. Được tạp chí danh tiếng Time Out vinh danh là một trong những đường phố thú vị nhất thế giới năm 2025, Vĩnh Khánh không chỉ là nơi để ăn, mà là một sân khấu văn hóa sống động. Dưới ánh đèn neon chớp nháy và làn khói bếp thơm lừng mùi bơ tỏi, hành phi, hàng chục quán ốc, lẩu, nướng đang chờ bạn khám phá. Hãy hít một hơi thật sâu, để mùi hương của biển cả và than hoa dẫn lối bạn vào cuộc hành trình vị giác đầy kịch tính này.',
    Description_En: 'Welcome to Vinh Khanh Food Street – District 4\'s sleepless paradise. As soon as you step through this gateway, you will feel the hustle, vibrancy, and enchanting rhythm of Saigon by night. Honored by Time Out magazine as one of the world\'s coolest streets in 2025, Vinh Khanh is not just a place to eat, but a living cultural stage. Under flashing neon lights and amid the fragrant smoke of garlic butter and fried shallots, dozens of snail, hotpot, and BBQ stalls await. Take a deep breath, and let the scent of the ocean and charcoal guide you on this dramatic culinary journey.',
    Description_Zh: '欢迎来到永庆美食街——第四郡的"不夜天堂"。当您踏入这个入口时，您将立即感受到西贡夜晚那繁忙、绚烂和迷人的节奏。永庆街被著名的Time Out杂志评为2025年世界最酷街道之一，这里不仅是用餐之地，更是一个充满活力的文化舞台。在闪烁的霓虹灯和飘散着蒜香黄油、油炸葱花香气的厨房烟雾下，数十家螺蛳、火锅和烧烤摊位等待您的探索。深呼吸，让海洋和木炭的香气引领您踏上这段充满戏剧性的美食之旅。',
    Location: { type: 'Point', coordinates: [106.7069244, 10.7607246] },
    Latitude: 10.7607246,
    Longitude: 106.7069244,
    Address: '534 Đường Vĩnh Khánh, Phường Khánh Hội, Quận 4, TP. Hồ Chí Minh',
    TriggerRadius: 80,
    Priority: 10,
    ZoneType: 'Area',
    ZoneLevel: 1,
    CooldownMinutes: 0,
    MaxPlaysPerSession: 1,
    SignatureDish: 'Không khí lễ hội đường phố (Street Festival Atmosphere)',
    FunFact: 'Được Time Out bình chọn là một trong những con phố thú vị nhất thế giới năm 2025.',
    OpeningHours: ['Mon-Sun 17:00-23:00'],
    OpeningHoursText: 'Hàng ngày: 17:00-23:00 (hoạt động theo quán xung quanh)',
    PhoneNumber: null,
    PriceLevel: null,
    AveragePrice: null,
    Rating: null,
    Category: 'Street Entrance',
    Tags: ['Time Out 2025', 'Food Street', 'Night Market', 'Cultural Hub'],
    ImageUrl: null,
    AudioUrl_Vi: null, AudioUrl_En: null, AudioUrl_Zh: null,
    IsActive: true,
    CreatedAt: new Date(), UpdatedAt: new Date()
  },

  {
    POI_ID: 2,
    Name_Vi: 'Ốc Vũ',
    Name_En: 'Vu Snails',
    Name_Zh: '武螺餐厅',
    Description_Vi: 'Ngay tại số 37 Vĩnh Khánh là Ốc Vũ, một cái tên được ví như "biểu tượng bình dân" của con phố này với hơn một thập kỷ đỏ lửa. Không hào nhoáng, cầu kỳ, Ốc Vũ chinh phục thực khách bằng sự chân thành trong từng món ăn. Nổi tiếng với nguồn hải sản tươi rói được tuyển chọn mỗi sáng từ chợ đầu mối Bình Điền, quán sở hữu thực đơn khổng lồ với hơn 50 món biến tấu. Điều khiến người ta nhớ mãi về Ốc Vũ chính là thứ nước chấm sốt me "thần thánh" – chua thanh, cay nhẹ, quện chặt vào từng con ốc, tạo nên một bản giao hưởng vị giác khó quên. Đây là điểm đến lý tưởng để bạn cảm nhận không khí nhậu đúng chất Sài Gòn: ồn ào, náo nhiệt và cực kỳ sảng khoái.',
    Description_En: 'Located at 37 Vinh Khanh is Vu Snails, often hailed as the "affordable icon" of this street with over a decade of history. Without pomp or circumstance, Vu Snails wins diners over with sincerity in every dish. Famous for fresh seafood selected every morning from Binh Dien wholesale market, the shop boasts a massive menu with over 50 variations. What makes people remember Vu Snails is their "divine" tamarind dipping sauce – tangy, slightly spicy, clinging to every snail, creating an unforgettable symphony of flavors. This is the ideal spot to experience the true Saigon drinking atmosphere: loud, bustling, and incredibly refreshing.',
    Description_Zh: '位于永庆街37号的武螺餐厅，被誉为这条街的"平民象征"，拥有十多年的辉煌历史。武螺没有华丽的装饰，而是以每道菜的真诚征服食客。餐厅以每天早上从平田批发市场精选的新鲜海鲜而闻名，菜单上有超过50种变化。让人们永远记住武螺的是他们"神圣"的罗望子蘸酱——酸爽微辣，紧紧包裹着每一只螺蛳，创造出难忘的味觉交响曲。这是体验正宗西贡饮酒氛围的理想场所：喧闹、热闹且极其畅快。',
    Location: { type: 'Point', coordinates: [106.7027047, 10.7614025] },
    Latitude: 10.7614025,
    Longitude: 106.7027047,
    Address: '37 Vĩnh Khánh, Phường Khánh Hội, Quận 4, TP. Hồ Chí Minh',
    TriggerRadius: 50,
    Priority: 7,
    ZoneType: 'Spot',
    ZoneLevel: 3,
    CooldownMinutes: 30,
    MaxPlaysPerSession: 1,
    SignatureDish: 'Ốc hương rang muối ớt, Sò điệp nướng mỡ hành',
    SignatureDishes: ['Ốc hương rang muối ớt', 'Sò điệp nướng mỡ hành', 'Ốc len xào me'],
    FunFact: 'Nước sốt me tại đây được xem là bí truyền, tạo nên thương hiệu riêng biệt.',
    OpeningHours: ['Mon-Sun 11:00-06:00'],
    OpeningHoursText: 'Hàng ngày: 11:00-06:00 sáng hôm sau',
    PhoneNumber: '+84 908 935 592',
    PriceLevel: 2,
    AveragePrice: 150000,
    Rating: 4.0,
    Category: 'Snails Restaurant',
    Tags: ['Street Food', 'Snails', 'Tamarind Sauce', 'Local Favorite'],
    ImageUrl: null,
    AudioUrl_Vi: null, AudioUrl_En: null, AudioUrl_Zh: null,
    IsActive: true,
    CreatedAt: new Date(), UpdatedAt: new Date()
  },

  {
    POI_ID: 3,
    Name_Vi: 'Ốc Thảo',
    Name_En: 'Thao Snails',
    Name_Zh: '草螺餐厅',
    Description_Vi: 'Bước đến số 383, bạn sẽ tìm thấy Ốc Thảo – một nốt trầm tinh tế giữa bản nhạc rock sôi động của Vĩnh Khánh. Khác với vẻ xô bồ thường thấy, Ốc Thảo chú trọng vào không gian rộng rãi, thoáng đãng và sạch sẽ, mang đến cảm giác thư thái hơn cho thực khách. Triết lý ẩm thực tại đây là tôn vinh vị ngọt tự nhiên của nguyên liệu. Món "Ốc len xào dừa" ở đây được đánh giá là cực phẩm với phần nước cốt dừa béo ngậy, đậm đà nhưng không hề gây ngán, hay món "Sò điệp nướng mỡ hành" với từng thớ thịt sò trắng ngần, mọng nước, thơm lừng mùi hành phi giòn rụm. Quán thậm chí mở cả ngày 24/7, hiếm có trên phố ốc.',
    Description_En: 'Arriving at number 383, you will find Thao Snails – a subtle note amidst the rock anthem of Vinh Khanh. Unlike the usual hustle, Thao Snails focuses on a spacious, airy, and clean space, offering a more relaxed vibe. The culinary philosophy here honors the natural sweetness of ingredients. The "Mud creeper snails in coconut milk" is considered a masterpiece with rich, creamy coconut sauce that never cloys, or the "Grilled scallops with scallion oil" featuring plump, juicy scallop meat fragrant with crispy fried shallots. The shop even operates 24/7, rare on the snail street.',
    Description_Zh: '来到383号，您会发现草螺餐厅——永庆街摇滚乐章中的一个精致低音符。与常见的喧嚣不同，草螺餐厅注重宽敞、通风和清洁的空间，为食客提供更轻松的氛围。这里的烹饪理念是尊重食材的天然甜味。"椰奶炒泥螺"被认为是杰作，浓郁的椰奶酱从不腻口，或是"葱油烤扇贝"，饱满多汁的扇贝肉散发着酥脆炸葱的香气。餐厅甚至24/7全天营业，在螺蛳街上实属罕见。',
    Location: { type: 'Point', coordinates: [106.7023636, 10.7616799] },
    Latitude: 10.7616799,
    Longitude: 106.7023636,
    Address: '383 Vĩnh Khánh, Phường Khánh Hội, Quận 4, TP. Hồ Chí Minh',
    TriggerRadius: 50,
    Priority: 7,
    ZoneType: 'Spot',
    ZoneLevel: 3,
    CooldownMinutes: 30,
    MaxPlaysPerSession: 1,
    SignatureDish: 'Ốc len xào dừa, Sò điệp nướng mỡ hành',
    SignatureDishes: ['Ốc len xào dừa', 'Sò điệp nướng mỡ hành', 'Mì xào ốc giác'],
    FunFact: 'Một trong số rất ít quán trên Vĩnh Khánh mở cửa 24/7, kể cả ban ngày.',
    OpeningHours: ['Mon-Sun 00:00-00:00'],
    OpeningHoursText: 'Mở cửa 24/7',
    PhoneNumber: '+84 932 117 078',
    PriceLevel: 2,
    AveragePrice: 180000,
    Rating: 3.8,
    Category: 'Snails Restaurant',
    Tags: ['Seafood', 'Coconut Flavor', 'Clean Space', 'Family Friendly', '24/7'],
    ImageUrl: null,
    AudioUrl_Vi: null, AudioUrl_En: null, AudioUrl_Zh: null,
    IsActive: true,
    CreatedAt: new Date(), UpdatedAt: new Date()
  },

  {
    POI_ID: 4,
    Name_Vi: 'Ốc Sáu Nở',
    Name_En: 'Sau No Snails',
    Name_Zh: '六绽螺餐厅',
    Description_Vi: 'Tọa lạc tại số 128 Vĩnh Khánh, Ốc Sáu Nở là hiện thân của văn hóa ốc vỉa hè Sài Gòn nguyên bản. Những chiếc bàn nhựa thấp, tiếng cười nói rôm rả, tiếng vỏ ốc lách cách tạo nên một bầu không khí không thể trộn lẫn. Sáu Nở nổi tiếng với các món ốc được tẩm ướp đậm đà, "bắt mồi" cực đỉnh. Đặc biệt, món Ốc hương sốt trứng muối ở đây là một huyền thoại: sốt trứng muối vàng ươm, béo bùi, mặn ngọt hài hòa, chấm kèm một mẩu bánh mì giòn tan thì không còn gì bằng. Thực khách quốc tế cũng ưa thích nơi đây vì có menu song ngữ và nhân viên thân thiện.',
    Description_En: 'Located at 128 Vinh Khanh, Sau No Snails embodies the original Saigon sidewalk snail culture. Low plastic tables, roaring laughter, and the clatter of snail shells create an unmistakable atmosphere. Sau No is famous for intensely marinated dishes that are perfect for drinking. Especially, the "Salted egg yolk sweet snails" here is legendary: golden, rich, savory-sweet sauce that pairs perfectly with a piece of crispy bread. International visitors also love this place for its bilingual menu and friendly staff.',
    Description_Zh: '位于永庆街128号的六绽螺餐厅体现了原汁原味的西贡路边螺文化。低矮的塑料桌、欢声笑语和螺壳的咔嗒声营造出独特的氛围。六绽螺以浓郁腌制的菜肴而闻名，是喝酒的绝佳搭配。特别是这里的"咸蛋黄香螺"已成传奇：金黄浓郁的咸甜酱汁搭配一块酥脆的面包，简直无与伦比。国际游客也因其双语菜单和友好的员工而喜欢这里。',
    Location: { type: 'Point', coordinates: [106.702942, 10.7609643] },
    Latitude: 10.7609643,
    Longitude: 106.702942,
    Address: '128 Vĩnh Khánh, Phường Khánh Hội, Quận 4, TP. Hồ Chí Minh',
    TriggerRadius: 50,
    Priority: 8,
    ZoneType: 'Spot',
    ZoneLevel: 3,
    CooldownMinutes: 30,
    MaxPlaysPerSession: 1,
    SignatureDish: 'Ốc hương sốt trứng muối, Nghêu hấp sả',
    SignatureDishes: ['Ốc hương sốt trứng muối', 'Nghêu hấp sả', 'Ốc len xào rau muống'],
    FunFact: 'Một trong những quán vỉa hè đời đầu, giữ trọn vẹn hồn cốt của phố ốc.',
    OpeningHours: ['Mon-Sun 16:00-02:30'],
    OpeningHoursText: 'Hàng ngày: 16:00-02:30',
    PhoneNumber: '+84 908 355 999',
    PriceLevel: 2,
    AveragePrice: 140000,
    Rating: 3.9,
    Category: 'Snails Restaurant',
    Tags: ['Sidewalk Culture', 'Late Night', 'Salted Egg', 'English Menu'],
    ImageUrl: null,
    AudioUrl_Vi: null, AudioUrl_En: null, AudioUrl_Zh: null,
    IsActive: true,
    CreatedAt: new Date(), UpdatedAt: new Date()
  },

  {
    POI_ID: 5,
    Name_Vi: 'Ốc Oanh',
    Name_En: 'Oanh Snails',
    Name_Zh: '莺螺餐厅',
    Description_Vi: 'Đây chính là "ngôi sao sáng nhất" của bầu trời Vĩnh Khánh – Ốc Oanh, quán ốc vinh dự được Michelin Guide trao tặng danh hiệu Bib Gourmand năm 2024. Với lịch sử hơn 20 năm, từ một gánh hàng rong nhỏ bé vươn lên thành thương hiệu quốc tế, Ốc Oanh là minh chứng cho sức hấp dẫn của ẩm thực Việt. Không gian cực kỳ rộng, có thể phục vụ hàng trăm thực khách cùng lúc, hải sản luôn được nhập tươi liên tục trong ngày. Món ăn làm nên tên tuổi của quán là "Ốc hương xào bơ tỏi": những con ốc to, chắc thịt ngập trong sốt bơ tỏi vàng óng, thơm nức mũi, chấm cùng bánh mì là sự kết hợp hoàn hảo.',
    Description_En: 'This is the "brightest star" of the Vinh Khanh sky – Oanh Snails, the snail shop honored with the Michelin Bib Gourmand title in 2024. With over 20 years of history, rising from a small street stall to an international brand, Oanh Snails is a testament to the allure of Vietnamese cuisine. The enormous space can serve hundreds of diners simultaneously, with seafood restocked continuously throughout the day. The dish that made their name is "Sweet snails stir-fried with garlic butter": large, firm snails submerged in golden, aromatic garlic butter sauce, perfectly paired with bread.',
    Description_Zh: '这是永庆街天空中"最闪亮的明星"——莺螺餐厅，这家螺蛳店荣幸地在2024年获得米其林必比登美食推介称号。拥有超过20年的历史，从一个小街摊成长为国际品牌，莺螺餐厅是越南美食魅力的见证。宽敞的空间可同时接待数百名食客，海鲜全天持续补货。让他们成名的菜肴是"蒜香黄油炒香螺"：大而结实的螺蛳浸泡在金黄芳香的蒜香黄油酱中，搭配面包简直完美。',
    Location: { type: 'Point', coordinates: [106.7032972, 10.7607194] },
    Latitude: 10.7607194,
    Longitude: 106.7032972,
    Address: '534 Vĩnh Khánh, Phường Khánh Hội, Quận 4, TP. Hồ Chí Minh',
    TriggerRadius: 60,
    Priority: 9,
    ZoneType: 'Spot',
    ZoneLevel: 3,
    CooldownMinutes: 30,
    MaxPlaysPerSession: 1,
    SignatureDish: 'Ốc hương xào bơ tỏi, Càng ghẹ rang muối',
    SignatureDishes: ['Ốc hương xào bơ tỏi', 'Càng ghẹ rang muối', 'Sò điệp nướng phô mai'],
    FunFact: 'Địa điểm duy nhất trên phố được Michelin vinh danh Bib Gourmand 2024.',
    OpeningHours: ['Mon-Sun 13:00-03:00'],
    OpeningHoursText: 'Hàng ngày: 13:00-03:00 sáng hôm sau (thường xuyên kín chỗ)',
    PhoneNumber: '+84 937 916 159',
    PriceLevel: 2,
    AveragePrice: 250000,
    Rating: 3.7,
    Category: 'Snails Restaurant',
    Tags: ['Michelin Bib Gourmand', 'International Fame', 'Garlic Butter', 'Premium Quality'],
    ImageUrl: null,
    AudioUrl_Vi: null, AudioUrl_En: null, AudioUrl_Zh: null,
    IsActive: true,
    CreatedAt: new Date(), UpdatedAt: new Date()
  },

  {
    POI_ID: 6,
    Name_Vi: 'A Fat Hot Pot',
    Name_En: 'A Fat Hot Pot',
    Name_Zh: '阿发火锅',
    Description_Vi: 'Tại số 668 Vĩnh Khánh, A Fat Hot Pot mở ra một cánh cửa thời gian, đưa bạn lạc vào không gian Hong Kong những năm 80-90 đầy hoài niệm. Với decor mang đậm chất điện ảnh TVB, những bảng hiệu neon rực rỡ và nhạc Hoa xưa cũ, quán tạo nên một trải nghiệm thị giác thú vị. "Ngôi sao" thực sự nằm ở nồi lẩu. A Fat nổi tiếng với Lẩu Trường Thọ xanh độc đáo và Lẩu Collagen trứ danh – nước dùng thanh ngọt không bột ngọt, bổ dưỡng, được ninh kỹ từ xương. Mô hình lẩu tự chọn với quầy sốt pha chế theo sở thích giúp bạn làm chủ bữa tiệc vị giác của mình. Thực khách đặc biệt ưa thích thịt bò Wagyu giá phải chăng tại đây.',
    Description_En: 'At 668 Vinh Khanh, A Fat Hot Pot opens a time portal, transporting you to the nostalgic atmosphere of 1980s-90s Hong Kong. With TVB-cinema style decor, vibrant neon signs, and old Cantonese music, the shop creates an exciting visual experience. The real "star" lies in the hot pot. A Fat is famous for its unique Green Longevity Hot Pot and renowned Collagen Hot Pot – clear, MSG-free, nutritious broth slow-cooked from bones. The self-service model with a DIY sauce station lets you master your flavor feast. Diners especially love the affordable Wagyu beef option.',
    Description_Zh: '在永庆街668号，阿发火锅打开了一扇时光之门，将您带入充满怀旧气息的80-90年代香港氛围。凭借浓郁的TVB电影风格装饰、绚丽的霓虹招牌和老式粤语音乐，这家店创造了令人兴奋的视觉体验。真正的"明星"在于火锅本身。阿发以其独特的绿色长寿火锅和著名的胶原蛋白火锅而闻名——清澈无味精的营养高汤由骨头慢炖而成。自助模式配有DIY酱料台，让您掌控自己的味觉盛宴。食客特别喜爱这里实惠的和牛选项。',
    Location: { type: 'Point', coordinates: [106.7035324, 10.7605856] },
    Latitude: 10.7605856,
    Longitude: 106.7035324,
    Address: '668 Vĩnh Khánh, Phường Khánh Hội, Quận 4, TP. Hồ Chí Minh',
    TriggerRadius: 50,
    Priority: 6,
    ZoneType: 'Spot',
    ZoneLevel: 3,
    CooldownMinutes: 30,
    MaxPlaysPerSession: 1,
    SignatureDish: 'Lẩu Trường Thọ (xanh), Lẩu Collagen',
    SignatureDishes: ['Lẩu Trường Thọ xanh', 'Lẩu Collagen', 'Thịt bò Wagyu'],
    FunFact: 'Không gian retro Hong Kong độc đáo bậc nhất Vĩnh Khánh, nước lẩu không bột ngọt.',
    OpeningHours: ['Mon-Sun 17:00-23:00'],
    OpeningHoursText: 'Hàng ngày: 17:00-23:00',
    PhoneNumber: '+84 903 070 002',
    PriceLevel: 2,
    AveragePrice: 200000,
    Rating: 4.3,
    Category: 'Hot Pot Restaurant',
    Tags: ['Hot Pot', 'Hong Kong Style', 'Instagram Worthy', 'No MSG', 'Wagyu'],
    ImageUrl: null,
    AudioUrl_Vi: null, AudioUrl_En: null, AudioUrl_Zh: null,
    IsActive: true,
    CreatedAt: new Date(), UpdatedAt: new Date()
  },

  {
    POI_ID: 7,
    Name_Vi: 'Chilli Lẩu Nướng Tự Chọn',
    Name_En: 'Chilli BBQ & Hot Pot',
    Name_Zh: '辣椒自助烧烤火锅',
    Description_Vi: 'Chilli tại 232 Vĩnh Khánh là thiên đường dành cho giới trẻ và những tín đồ mê đồ nướng tự chọn. Quán mang đến sự phóng khoáng, tự do với mô hình BBQ ngoài trời ngay trên vỉa hè – bạn tự tay nướng thịt trên bếp than ngay bàn ăn, tạo nên trải nghiệm cực kỳ sôi động. Thực đơn là một cuộc diễu hành của protein: từ bò Mỹ cuộn nấm, ba chỉ heo sốt BBQ đến các loại hải sản tươi rói. Đừng bỏ qua món "Lẩu Hàu Kimchi" trứ danh – sự kết hợp táo bạo giữa vị chua cay của kim chi Hàn Quốc và vị ngọt béo mọng nước của hàu sữa Việt Nam.',
    Description_En: 'Chilli at 232 Vinh Khanh is a paradise for youngsters and fans of DIY BBQ. The place offers an exciting outdoor sidewalk BBQ experience – you grill meat yourself on a charcoal grill right at your table. The menu is a parade of protein: from mushroom-wrapped US beef, pork belly with BBQ sauce to fresh seafood. Don\'t miss the famous "Kimchi Oyster Hotpot" – a bold combination of the spicy-sour kick of Korean kimchi and the rich, juicy sweetness of Vietnamese milk oysters.',
    Description_Zh: '位于永庆街232号的辣椒是年轻人和DIY烧烤爱好者的天堂。这个地方提供令人兴奋的户外路边烧烤体验——您可以在桌边的炭火烤炉上亲自烤肉。菜单是蛋白质的盛宴：从蘑菇卷美国牛肉、BBQ酱五花肉到新鲜海鲜。不要错过著名的"泡菜生蚝火锅"——韩国泡菜的酸辣与越南奶油生蚝的浓郁多汁甜味大胆结合。',
    Location: { type: 'Point', coordinates: [106.7036324, 10.760693] },
    Latitude: 10.760693,
    Longitude: 106.7036324,
    Address: '232/105 Vĩnh Khánh, Phường Khánh Hội, Quận 4, TP. Hồ Chí Minh',
    TriggerRadius: 50,
    Priority: 6,
    ZoneType: 'Spot',
    ZoneLevel: 3,
    CooldownMinutes: 30,
    MaxPlaysPerSession: 1,
    SignatureDish: 'Lẩu hàu Kimchi, Sụn gà trứng muối',
    SignatureDishes: ['Lẩu hàu Kimchi', 'Sụn gà trứng muối', 'Bò Mỹ cuộn nấm'],
    FunFact: 'Trải nghiệm tự nướng ngoài trời trên vỉa hè – sôi động nhất phố!',
    OpeningHours: ['Mon-Sun 16:00-00:30'],
    OpeningHoursText: 'Hàng ngày: 16:00-00:30',
    PhoneNumber: '+84 902 935 667',
    PriceLevel: 2,
    AveragePrice: 180000,
    Rating: 3.8,
    Category: 'BBQ & Hot Pot',
    Tags: ['Youth Favorite', 'Outdoor BBQ', 'Korean Fusion', 'Group Dining'],
    ImageUrl: null,
    AudioUrl_Vi: null, AudioUrl_En: null, AudioUrl_Zh: null,
    IsActive: true,
    CreatedAt: new Date(), UpdatedAt: new Date()
  },

  {
    POI_ID: 8,
    Name_Vi: 'Alo Quán - Seafood & Beer',
    Name_En: 'Alo Quan - Beer & Seafood',
    Name_Zh: '喂餐厅 - 海鲜啤酒',
    Description_Vi: 'Tọa lạc tại 333 Vĩnh Khánh, Alo Quán mang đến một làn gió hiện đại và "chill" hơn cho con phố. Không gian mở thoáng đãng, thiết kế trẻ trung với bảng neon bắt mắt, nơi đây phù hợp cho những cuộc vui xuyên đêm. Thực đơn của Alo Quán đa dạng đến bất ngờ: từ ốc ếch cho đến ốc, ếch, cá, tôm đủ kiểu chế biến. Nhân viên nói tiếng Anh tốt, thân thiện – điểm cộng lớn cho khách quốc tế. Lưu ý: bảng Google Maps có thể chưa chính xác hoàn toàn, cứ tìm biển neon Alo Quán là thấy.',
    Description_En: 'Located at 333 Vinh Khanh, Alo Quan brings a modern, "chiller" breeze to the street. Open, airy space with eye-catching neon signs, perfect for all-night parties. Alo Quan\'s menu is surprisingly diverse: from snails and frogs to fish and shrimp prepared in every way. Staff speak English well and are friendly – a big plus for international visitors. Note: Google Maps pin may not be perfectly accurate; just look for the Alo Quan neon sign.',
    Description_Zh: '位于永庆街333号的喂餐厅为这条街带来了现代化和更"轻松"的气息。开放通风的空间配有醒目的霓虹招牌，非常适合通宵派对。喂餐厅的菜单令人惊讶地多样：从螺蛳、青蛙到鱼、虾，各种烹饪方式一应俱全。员工英语流利友好——对国际游客是大加分。注意：谷歌地图标注可能不完全准确，找到喂餐厅霓虹招牌即可。',
    Location: { type: 'Point', coordinates: [106.7047634, 10.7609754] },
    Latitude: 10.7609754,
    Longitude: 106.7047634,
    Address: '333 Vĩnh Khánh, Phường Khánh Hội, Quận 4, TP. Hồ Chí Minh',
    TriggerRadius: 60,
    Priority: 7,
    ZoneType: 'Spot',
    ZoneLevel: 3,
    CooldownMinutes: 30,
    MaxPlaysPerSession: 1,
    SignatureDish: 'Tôm sống sốt Thái, Ếch chiên giòn',
    SignatureDishes: ['Tôm sống sốt Thái', 'Ếch chiên giòn', 'Sò điệp nướng phô mai'],
    FunFact: 'Nhân viên nói tiếng Anh tốt, điểm đến thân thiện nhất với du khách quốc tế trên phố.',
    OpeningHours: ['Mon-Sun 11:00-03:00'],
    OpeningHoursText: 'Hàng ngày: 11:00-03:00 sáng hôm sau',
    PhoneNumber: '+84 888 488 333',
    PriceLevel: 2,
    AveragePrice: 200000,
    Rating: 3.8,
    Category: 'Seafood & Beer',
    Tags: ['English Speaking Staff', 'Open Space', 'Late Night', 'Tourist Friendly'],
    ImageUrl: null,
    AudioUrl_Vi: null, AudioUrl_En: null, AudioUrl_Zh: null,
    IsActive: true,
    CreatedAt: new Date(), UpdatedAt: new Date()
  },

  {
    POI_ID: 9,
    Name_Vi: 'Ốc Đào 2',
    Name_En: 'Dao Snails 2',
    Name_Zh: '桃螺餐厅2号店',
    Description_Vi: 'Ốc Đào 2 là một trong những điểm đến được khách quốc tế yêu thích nhất trên phố Vĩnh Khánh, với gần 800 đánh giá trên Google. Điểm mạnh của quán: menu có ảnh minh họa to rõ ràng, dễ gọi dù không biết tiếng Việt. Nhân viên nhiệt tình hướng dẫn, không ngại bóc ốc giúp khách. Thực đơn phong phú từ ốc đến mì xào hải sản – đặc biệt món "Mì xào ốc dao" bùi béo, đậm đà được nhiều thực khách gọi là không thể thiếu để "lót bụng" sau một buổi ốc. Đây cũng là quán hoạt động đến tận 1 giờ sáng, phù hợp với lịch trình khám phá về đêm.',
    Description_En: 'Dao Snails 2 is one of the most loved spots by international visitors on Vinh Khanh street, with nearly 800 Google reviews. The restaurant\'s strengths: a large picture menu easy to order from even without Vietnamese language skills, and staff happy to crack open snails for guests. The extensive menu ranges from snails to stir-fried seafood noodles – especially the "Stir-fried noodles with razor clams" which many diners call essential "carb loading" after a snail feast. The venue operates until 1 AM, ideal for night exploration schedules.',
    Description_Zh: '桃螺2号店是永庆街上最受国际游客喜爱的地点之一，在谷歌上有近800条评论。餐厅的优势：有大图菜单，即使不懂越南语也容易点餐，员工乐意为客人打开螺蛳。从螺蛳到海鲜炒面，菜单内容丰富——特别是"刀蛤炒面"，许多食客认为是螺蛳大餐后必不可少的"碳水补充"。该场所营业至凌晨1点，非常适合夜间探索行程。',
    Location: { type: 'Point', coordinates: [106.7049786, 10.7611372] },
    Latitude: 10.7611372,
    Longitude: 106.7049786,
    Address: '232/123 Vĩnh Khánh, Phường Khánh Hội, Quận 4, TP. Hồ Chí Minh',
    TriggerRadius: 50,
    Priority: 8,
    ZoneType: 'Spot',
    ZoneLevel: 3,
    CooldownMinutes: 30,
    MaxPlaysPerSession: 1,
    SignatureDish: 'Ốc nướng bơ tỏi, Mì xào ốc dao',
    SignatureDishes: ['Ốc nướng bơ tỏi', 'Mì xào ốc dao', 'Nghêu nướng mỡ hành'],
    FunFact: 'Gần 800 đánh giá Google – quán được khách quốc tế review nhiều nhất phố Vĩnh Khánh!',
    OpeningHours: ['Mon-Sun 11:00-01:00'],
    OpeningHoursText: 'Hàng ngày: 11:00-01:00 sáng hôm sau',
    PhoneNumber: '+84 352 499 883',
    PriceLevel: 2,
    AveragePrice: 160000,
    Rating: 4.2,
    Category: 'Snails Restaurant',
    Tags: ['Tourist Favorite', 'Picture Menu', 'International', 'Late Night'],
    ImageUrl: null,
    AudioUrl_Vi: null, AudioUrl_En: null, AudioUrl_Zh: null,
    IsActive: true,
    CreatedAt: new Date(), UpdatedAt: new Date()
  },

  {
    POI_ID: 10,
    Name_Vi: 'Lãng Restaurant',
    Name_En: 'Lang Restaurant',
    Name_Zh: '浪餐厅',
    Description_Vi: 'Lãng Restaurant tại 531 Vĩnh Khánh là một trong những địa điểm mở cửa muộn nhất phố – đến tận 4 giờ sáng – trở thành điểm đến yêu thích của những "cú đêm" Sài Gòn. Khác với hình dung về quán nhậu bình thường, Lãng gây bất ngờ với thực đơn phong phú và sáng tạo, đặc biệt là món gà: "Gà nướng cơm trúc" giòn rụm với cơm trúc thơm lừng được khách khen nức nở. Quán còn phục vụ nhạc sống vào một số buổi tối, tạo không khí vô cùng sảng khoái. Đây là nơi để vừa ăn ngon, vừa nhâm nhi bia lạnh và ngắm nhìn phố đêm tấp nập.',
    Description_En: 'Lang Restaurant at 531 Vinh Khanh is one of the latest-operating spots on the street – until 4 AM – becoming a favorite haunt for Saigon night owls. Unlike typical drinking dens, Lang surprises with a rich and creative menu, especially chicken: "Bamboo rice grilled chicken" crispy and fragrant has won rave reviews. The restaurant also features live music on some evenings, creating an incredibly lively atmosphere. It\'s the place to eat well, sip cold beer, and watch the bustling night street.',
    Description_Zh: '位于永庆街531号的浪餐厅是街上营业最晚的场所之一——直到凌晨4点——成为西贡夜猫子的最爱去处。与普通饮酒场所不同，浪餐厅以其丰富创意的菜单令人惊喜，尤其是鸡肉类："竹米烤鸡"酥脆香气四溢，获得食客热烈好评。餐厅在某些傍晚还有现场音乐表演，营造出极其活跃的氛围。这是一个边吃美食、边品冰啤、边欣赏繁华夜街的好地方。',
    Location: { type: 'Point', coordinates: [106.7054162, 10.7611131] },
    Latitude: 10.7611131,
    Longitude: 106.7054162,
    Address: '531 Vĩnh Khánh, Phường Khánh Hội, Quận 4, TP. Hồ Chí Minh',
    TriggerRadius: 50,
    Priority: 7,
    ZoneType: 'Spot',
    ZoneLevel: 3,
    CooldownMinutes: 30,
    MaxPlaysPerSession: 1,
    SignatureDish: 'Gà nướng cơm trúc, Ốc hương rang me',
    SignatureDishes: ['Gà nướng cơm trúc', 'Ốc hương rang me', 'Chân gà sả tắc'],
    FunFact: 'Mở đến 4 giờ sáng và có nhạc sống – bữa tiệc đêm muộn hoàn hảo nhất phố.',
    OpeningHours: ['Mon-Sun 15:00-04:00'],
    OpeningHoursText: 'Hàng ngày: 15:00-04:00 sáng hôm sau',
    PhoneNumber: '+84 888 833 111',
    PriceLevel: 2,
    AveragePrice: 180000,
    Rating: 4.3,
    Category: 'Late Night Dining',
    Tags: ['Late Night', 'Live Music', 'Night Owls', 'Creative Menu'],
    ImageUrl: null,
    AudioUrl_Vi: null, AudioUrl_En: null, AudioUrl_Zh: null,
    IsActive: true,
    CreatedAt: new Date(), UpdatedAt: new Date()
  },

  {
    POI_ID: 11,
    Name_Vi: 'Ớt Xiêm Quán',
    Name_En: 'Ot Xiem Quan',
    Name_Zh: '暹罗辣椒餐厅',
    Description_Vi: 'Ớt Xiêm Quán tại số 568 Vĩnh Khánh nổi tiếng với các món ăn cay nồng đích thực, đúng như cái tên của mình. Đây là thiên đường dành cho những tín đồ của vị cay, với menu đa dạng từ ốc, hải sản đến các món nướng và xào, tất cả đều có thể được tùy chỉnh độ cay theo sở thích – kể cả level "ớt tử thần" thử thách dành cho người dũng cảm. Không gian quán nhộn nhịp, đầy năng lượng. Món "Ốc hương xào ớt hiểm" và "Tôm sú nướng ớt" là những lựa chọn không thể bỏ qua.',
    Description_En: 'Ot Xiem Quan at 568 Vinh Khanh is famous for its genuinely fiery dishes, true to its name. This is a paradise for spice lovers, with a diverse menu from snails and seafood to grilled and stir-fried dishes, all customizable in spiciness – including a "death chili" level challenge for the brave. The bustling space is full of energy. "Spicy stir-fried sweet snails" and "Grilled tiger prawns with chili" are must-try choices.',
    Description_Zh: '位于永庆街568号的暹罗辣椒餐厅以其真正火辣的菜肴而闻名，名副其实。这是辣味爱好者的天堂，从螺蛳、海鲜到烤制和炒菜，所有菜品的辣度都可以根据喜好定制——包括为勇敢者设计的"死亡辣椒"挑战级别。热闹的空间充满活力。"辣炒香螺"和"辣烤虎虾"是不容错过的选择。',
    Location: { type: 'Point', coordinates: [106.7057009, 10.7611663] },
    Latitude: 10.7611663,
    Longitude: 106.7057009,
    Address: '568 Vĩnh Khánh, Phường Khánh Hội, Quận 4, TP. Hồ Chí Minh',
    TriggerRadius: 50,
    Priority: 7,
    ZoneType: 'Spot',
    ZoneLevel: 3,
    CooldownMinutes: 30,
    MaxPlaysPerSession: 1,
    SignatureDish: 'Ốc hương xào ớt hiểm, Tôm sú nướng ớt',
    SignatureDishes: ['Ốc hương xào ớt hiểm', 'Tôm sú nướng ớt', 'Sò huyết nướng mỡ hành'],
    FunFact: 'Thử thách level "ớt tử thần" – bạn có đủ dũng cảm không?',
    OpeningHours: ['Mon-Sun 17:00-01:30'],
    OpeningHoursText: 'Hàng ngày: 17:00-01:30 sáng hôm sau',
    PhoneNumber: '+84 397 190 292',
    PriceLevel: 2,
    AveragePrice: 170000,
    Rating: 4.2,
    Category: 'Spicy Seafood',
    Tags: ['Spicy Food', 'Customizable Heat', 'Death Chili Challenge', 'Energetic'],
    ImageUrl: null,
    AudioUrl_Vi: null, AudioUrl_En: null, AudioUrl_Zh: null,
    IsActive: true,
    CreatedAt: new Date(), UpdatedAt: new Date()
  },

  {
    POI_ID: 12,
    Name_Vi: 'Bún Cá Châu Đốc Dì Tư Vĩnh Khánh',
    Name_En: 'Di Tu Chau Doc Fish Noodle Soup',
    Name_Zh: '四姨周德鱼粉',
    Description_Vi: 'Bún Cá Châu Đốc Dì Tư tại số 75 Vĩnh Khánh là điểm dừng chân hoàn hảo để bắt đầu hoặc kết thúc hành trình khám phá phố đêm. Tô bún cá với đầu cá lóc to, nhiều thịt, nước dùng ngọt thanh từ cá tươi nấu cùng sả, nghệ và gia vị đặc trưng miền Tây Nam Bộ. Quán mở từ 6 giờ sáng – lý tưởng cho bữa sáng sau đêm vui chơi thâu đêm, hoặc ghé vào buổi chiều trước khi phố ốc bắt đầu nhộn nhịp. Giá cả siêu bình dân, chỉ 70.000đ cho một tô đầy ắp.',
    Description_En: 'Di Tu Chau Doc Fish Noodle Soup at 75 Vinh Khanh is the perfect stop to start or end a night street exploration. A bowl of fish noodle soup with a large, meaty snakehead fish head, sweet and clear broth cooked with lemongrass, turmeric, and distinctive Southern Vietnamese spices. The shop opens from 6 AM – ideal for breakfast after an all-night adventure, or a stop in the afternoon before the snail street gets busy. Very affordable at just 70,000 VND for a generous bowl.',
    Description_Zh: '位于永庆街75号的四姨周德鱼粉是开始或结束夜街探索之旅的完美停靠点。一碗鱼粉配上大而肉质丰富的黑鱼头，清甜的高汤用新鲜鱼、香茅、姜黄和南越特有香料烹制而成。餐厅从早上6点开始营业——非常适合通宵娱乐后的早餐，或在螺蛳街开始热闹之前的下午顺路光顾。价格超级实惠，一大碗仅需70,000越南盾。',
    Location: { type: 'Point', coordinates: [106.7066391, 10.7609233] },
    Latitude: 10.7609233,
    Longitude: 106.7066391,
    Address: '320/79 Vĩnh Khánh, Phường Khánh Hội, Quận 4, TP. Hồ Chí Minh',
    TriggerRadius: 40,
    Priority: 7,
    ZoneType: 'Spot',
    ZoneLevel: 3,
    CooldownMinutes: 30,
    MaxPlaysPerSession: 1,
    SignatureDish: 'Bún cá đầu cá lóc, Bún cá thêm lòng',
    SignatureDishes: ['Bún cá đầu cá lóc', 'Bún cá thêm lòng', 'Bún riêu cá'],
    FunFact: 'Chỉ 70.000đ cho tô bún cá đầu cá lóc to đùng – ngon nhất khi ăn lúc 6 giờ sáng!',
    OpeningHours: ['Mon-Sun 06:00-02:00'],
    OpeningHoursText: 'Hàng ngày: 06:00-02:00 sáng hôm sau',
    PhoneNumber: '+84 394 444 177',
    PriceLevel: 1,
    AveragePrice: 70000,
    Rating: 4.6,
    Category: 'Breakfast & Noodles',
    Tags: ['Breakfast', 'Southern Cuisine', 'Hangover Cure', 'Budget Friendly'],
    ImageUrl: null,
    AudioUrl_Vi: null, AudioUrl_En: null, AudioUrl_Zh: null,
    IsActive: true,
    CreatedAt: new Date(), UpdatedAt: new Date()
  },

  {
    POI_ID: 13,
    Name_Vi: 'Ốc Phát',
    Name_En: 'Phat Snails',
    Name_Zh: '发螺餐厅',
    Description_Vi: 'Ngay tại số 361 Vĩnh Khánh, Ốc Phát là một trong những cái tên quen thuộc nhất với dân nhậu Quận 4. Quán nổi bật với không gian rộng rãi, mát mẻ ngay đầu phần giữa con phố. Điểm khác biệt của Ốc Phát chính là thực đơn phong phú không chỉ có ốc: từ "Cá tai tượng chiên xù" giòn rụm, thịt trắng ngần đến "Ốc len xào rau muống" dân dã mà đậm đà. Quán cũng được nhiều khách quốc tế ưa thích vì có Leng Zaab – món súp Thái cay đậm gần tương đương chất lượng Jodd Fairs Bangkok. Mở cửa đến tận 4 giờ sáng (trừ Thứ Năm).',
    Description_En: 'At 361 Vinh Khanh, Phat Snails is one of the most familiar names to District 4\'s food lovers. The restaurant stands out with its spacious setting in the middle section of the street. What sets Phat Snails apart is its rich menu beyond snails: from crispy "Elephant-ear fish" with snowy white meat to the homely "Razor clams stir-fried with water spinach." The restaurant is also popular with international visitors for Leng Zaab – a spicy Thai soup of near-equivalent quality to Bangkok\'s Jodd Fairs. Open until 4 AM (except Thursday).',
    Description_Zh: '位于永庆街361号的发螺餐厅是第四郡饮食爱好者最熟悉的名字之一。餐厅以其宽敞的空间在街道中段脱颖而出。发螺的与众不同之处在于其丰富的菜单，不仅仅是螺蛳：从酥脆的"象耳鱼"（肉质雪白）到朴实而醇厚的"角螺炒空心菜"。餐厅还因Leng Zaab而受到国际游客欢迎——一种辣味泰国汤，质量接近曼谷Jodd Fairs。营业至凌晨4点（周四除外）。',
    Location: { type: 'Point', coordinates: [106.7020937, 10.7619545] },
    Latitude: 10.7619545,
    Longitude: 106.7020937,
    Address: '237/42/46 Vĩnh Khánh, Phường Khánh Hội, Quận 4, TP. Hồ Chí Minh',
    TriggerRadius: 50,
    Priority: 7,
    ZoneType: 'Spot',
    ZoneLevel: 3,
    CooldownMinutes: 30,
    MaxPlaysPerSession: 1,
    SignatureDish: 'Cá tai tượng chiên xù, Ốc len xào rau muống',
    SignatureDishes: ['Cá tai tượng chiên xù', 'Ốc len xào rau muống', 'Leng Zaab Thái'],
    FunFact: 'Leng Zaab ở đây được khách quốc tế khen gần sánh kịp Jodd Fairs Bangkok!',
    OpeningHours: ['Mon-Sun 13:00-04:00'],
    OpeningHoursText: 'Hàng ngày: 13:00-04:00 (Thứ Năm: 13:00-00:00)',
    PhoneNumber: '+84 906 039 288',
    PriceLevel: 2,
    AveragePrice: 160000,
    Rating: 3.7,
    Category: 'Snails Restaurant',
    Tags: ['Diverse Menu', 'Late Night', 'Thai Soup', 'International Friendly'],
    ImageUrl: null,
    AudioUrl_Vi: null, AudioUrl_En: null, AudioUrl_Zh: null,
    IsActive: true,
    CreatedAt: new Date(), UpdatedAt: new Date()
  },

  {
    POI_ID: 14,
    Name_Vi: 'Tỷ Muội Quán',
    Name_En: 'Ty Muoi Quan (Sisters Restaurant)',
    Name_Zh: '姐妹餐厅',
    Description_Vi: 'Tỷ Muội Quán – "Quán hai chị em" – tại Vĩnh Khánh là một trong những địa chỉ được đánh giá cao nhất phố với rating 4.5 sao. Không gian quán rộng rãi, thoải mái, phục vụ nhiều món đa dạng: hải sản, ốc, thịt nướng và cả lẩu. Điểm đặc biệt của Tỷ Muội là bia lên bàn cực nhanh – quan trọng không kém gì chất lượng thức ăn khi đi nhậu! Giá cả hợp lý, không gian tốt và thái độ phục vụ chu đáo khiến quán trở thành lựa chọn yêu thích cho cả nhóm bạn lẫn gia đình.',
    Description_En: 'Ty Muoi Quan – "The Sisters Restaurant" – on Vinh Khanh is one of the highest-rated spots on the street with a 4.5-star rating. The spacious, comfortable space serves a wide range of dishes: seafood, snails, grilled meats and hotpot. What\'s special about Ty Muoi is that beers arrive at the table super fast – just as important as food quality when you\'re out for drinks! Reasonable prices, good space, and attentive service make it a favorite choice for both friend groups and families.',
    Description_Zh: '"姐妹餐厅"位于永庆街，是街上评分最高的场所之一，拥有4.5星的评分。宽敞舒适的空间供应多种多样的菜肴：海鲜、螺蛳、烤肉和火锅。姐妹餐厅的特别之处在于啤酒上桌极快——这在外出喝酒时与食物质量同等重要！合理的价格、良好的空间和周到的服务使其成为朋友聚会和家庭用餐的最爱选择。',
    Location: { type: 'Point', coordinates: [106.7051793, 10.7613487] },
    Latitude: 10.7613487,
    Longitude: 106.7051793,
    Address: '232/59 Vĩnh Khánh, Phường Khánh Hội, Quận 4, TP. Hồ Chí Minh',
    TriggerRadius: 50,
    Priority: 7,
    ZoneType: 'Spot',
    ZoneLevel: 3,
    CooldownMinutes: 30,
    MaxPlaysPerSession: 1,
    SignatureDish: 'Hải sản tươi, Bia siêu nhanh',
    SignatureDishes: ['Hải sản tươi các loại', 'Lẩu hải sản', 'Thịt nướng'],
    FunFact: '4.5 sao – quán được rating cao nhất phố. Và bia lên bàn nhanh nhất!',
    OpeningHours: ['Mon-Sun 16:00-00:00'],
    OpeningHoursText: 'Hàng ngày: 16:00-00:00 (mở muộn)',
    PhoneNumber: '+84 788 792 556',
    PriceLevel: 1,
    AveragePrice: 190000,
    Rating: 4.5,
    Category: 'Seafood Restaurant',
    Tags: ['Highest Rated', 'Fast Beer', 'Family Friendly', 'Group Dining'],
    ImageUrl: null,
    AudioUrl_Vi: null, AudioUrl_En: null, AudioUrl_Zh: null,
    IsActive: true,
    CreatedAt: new Date(), UpdatedAt: new Date()
  }

];

db.pois.insertMany(pois);

db.counters.updateOne(
  { _id: 'poi_id' },
  { $set: { Value: 15 } }
);
